
export default {
    SET_LOGIN_STATUS: 'SET_LOGIN_STATUS',
    SET_INDEX_PARAMS: 'SET_INDEX_PARAMS',
    GET_QHLFXTOP_THREE: 'GET_QHLFXTOP_THREE',
    GET_QHLFX_BOTTOM_SIX: 'GET_QHLFX_BOTTOM_SIX',
};
